export const dataFromAPI = [
  {
    id: 1,
    first_name: 'Bernard',
    last_name: "O'Gorman",
    email: 'bogorman0@seattletimes.com',
    gender: 'Male',
    ip_address: '222.37.112.235',
  },
  {
    id: 2,
    first_name: 'Harcourt',
    last_name: 'Harbard',
    email: 'hharbard1@digg.com',
    gender: 'Bigender',
    ip_address: '106.114.195.111',
  },
  {
    id: 3,
    first_name: 'Penni',
    last_name: 'Jerok',
    email: 'pjerok2@chronoengine.com',
    gender: 'Female',
    ip_address: '62.3.45.104',
  },
  {
    id: 4,
    first_name: 'Goran',
    last_name: 'Tordoff',
    email: 'gtordoff3@ezinearticles.com',
    gender: 'Male',
    ip_address: '138.20.230.163',
  },
  {
    id: 5,
    first_name: 'Anica',
    last_name: 'Dibb',
    email: 'adibb4@indiatimes.com',
    gender: 'Female',
    ip_address: '192.71.105.50',
  },
  {
    id: 6,
    first_name: 'Aluin',
    last_name: 'Bridell',
    email: 'abridell5@unblog.fr',
    gender: 'Male',
    ip_address: '150.167.64.205',
  },
  {
    id: 7,
    first_name: 'Walden',
    last_name: 'Kitcatt',
    email: 'wkitcatt6@weather.com',
    gender: 'Male',
    ip_address: '215.51.200.116',
  },
  {
    id: 8,
    first_name: 'Tybalt',
    last_name: 'Leisman',
    email: 'tleisman7@tripadvisor.com',
    gender: 'Male',
    ip_address: '134.255.66.2',
  },
  {
    id: 9,
    first_name: 'Saidee',
    last_name: 'Gelder',
    email: 'sgelder8@mapquest.com',
    gender: 'Female',
    ip_address: '194.99.245.112',
  },
  {
    id: 10,
    first_name: 'Ryann',
    last_name: 'Pitone',
    email: 'rpitone9@canalblog.com',
    gender: 'Female',
    ip_address: '74.59.196.211',
  },
];
